from pydantic import BaseModel, Field, field_validator, HttpUrl, ConfigDict
from typing import List, Optional, Literal

# --- Import Schemas from Services/Core ---
from ...core.schemas import UsageStatistics # SearchTask is defined in core
from ...core.config import LLMConfig
from ..services.search import SearchResult # Import SearchResult from the service


# --- Schemas Specific to Deep Research Agency ---

class SearchTask(BaseModel):
    """Represents a single search task generated by the Planner LLM."""
    model_config = ConfigDict(extra='ignore')
    query: str = Field(..., description="The search query string to execute.", min_length=1)
    endpoint: str = Field("/search", description="The Serper API endpoint to target (e.g., /search, /scholar).")
    num_results: int = Field(5, description="Desired number of search results.", ge=1, le=20)
    reasoning: Optional[str] = Field(None, description="Planner's reasoning for generating this specific search task.")

    @field_validator('endpoint')
    def validate_endpoint(cls, v: str) -> str:
        allowed_endpoints = ['/search', '/scholar', '/news']
        if v not in allowed_endpoints:
            raise ValueError(f"Invalid endpoint '{v}'. Allowed: {allowed_endpoints}")
        return v

class SectionItem(BaseModel):
    """Defines a single section within the writing plan."""
    model_config = ConfigDict(extra='ignore')
    title: str = Field(..., description="Title for this section of the report.", min_length=1)
    guidance: str = Field(..., description="Specific instructions or guidance for writing this section.", min_length=1)

class WritingPlan(BaseModel):
    """Defines the structure and directives for the final report, generated by the Planner LLM."""
    model_config = ConfigDict(extra='ignore')
    overall_goal: str = Field(..., description="The main objective or purpose of the research report.", min_length=1)
    desired_tone: Optional[str] = Field(None, description="Preferred writing style or tone (e.g., formal, neutral, technical).")
    sections: List[SectionItem] = Field(..., description="An ordered list of sections that should constitute the report.", min_items=1)
    additional_directives: Optional[List[str]] = Field(None, description="Any extra high-level instructions for the Writer LLM.")

    @property
    def outline(self) -> List[str]:
        """Provides a simple list of section titles, primarily for backward compatibility or simple display."""
        return [section.title for section in self.sections]

class PlannerOutput(BaseModel):
    """Validates the structured JSON output expected from the Planner LLM."""
    model_config = ConfigDict(extra='ignore')
    search_tasks: List[SearchTask] = Field(..., description="List of search tasks to be executed based on the user query.", min_items=1)
    writing_plan: WritingPlan = Field(..., description="Detailed plan guiding the structure and content of the final report.")

class SourceSummary(BaseModel):
    """Represents processed information derived from a single web source, either a summary or aggregated chunks, used within the agency orchestration."""
    model_config = ConfigDict(extra='ignore')
    title: str = Field(..., description="The title of the web source (e.g., from <title> tag or search result).", min_length=1)
    link: HttpUrl = Field(..., description="The URL of the original web source.")
    content: str = Field(..., description="The processed content: either an LLM-generated summary or concatenated relevant text chunks.", min_length=1)
    content_type: Literal['summary', 'chunks'] = Field(..., description="Specifies whether the 'content' field holds a summary or concatenated chunks.")
    rank: Optional[int] = Field(None, description="Sequential citation rank assigned during processing.")
    # Removed original_title as likely unused

# --- Removed Chunk Schema ---
# class Chunk(BaseModel):
#     """Represents a single chunk of relevant text extracted from a source document."""
#     model_config = ConfigDict(extra='ignore')
#     content: str = Field(..., description="The text content of the chunk.", min_length=1)
#     link: HttpUrl = Field(..., description="The URL of the original source document.")
#     title: str = Field(..., description="The title of the original source document.")
#     relevance_score: Optional[float] = Field(None, description="Score assigned by the reranker indicating relevance to the query.")
#     rank: Optional[int] = Field(None, description="Sequential rank assigned during processing (e.g., for citation).")

class SearchRequest(BaseModel):
    """Validates a search request extracted from the Writer/Refiner LLM's output (e.g., <search_request query='...'>)."""
    model_config = ConfigDict(extra='ignore')
    query: str = Field(..., description="The specific search query requested by the LLM to gather more information.", min_length=1)

class WriterOutput(BaseModel):
    """Structured output for the Writer and Refiner agents."""
    model_config = ConfigDict(extra='allow') # Allow extra fields temporarily if needed, tighten later
    report_content: str = Field(..., description="The generated report content in Markdown format.")
    requested_searches: Optional[List[SearchRequest]] = Field(None, description="Optional list of search tasks requested by the agent if critical information is missing.")

# --- API Schemas (Will move to app/api/ later) ---

class ResearchRequest(BaseModel):
    """Request schema for the main `/research` endpoint."""
    model_config = ConfigDict(extra='ignore')
    query: str = Field(..., min_length=10, description="The user's research query.")
    # Optional config overrides for LLMs (Keep these)
    planner_llm_config: Optional[LLMConfig] = Field(None, description="Override default planner LLM settings.")
    summarizer_llm_config: Optional[LLMConfig] = Field(None, description="Override default summarizer LLM settings.")
    writer_llm_config: Optional[LLMConfig] = Field(None, description="Override default writer LLM settings.")
    max_search_tasks: Optional[int] = Field(None, description="Override maximum initial search tasks.")
    llm_provider: Optional[Literal['google', 'openrouter']] = Field(None, description="Override the default LLM provider for this request.")


from ...core.schemas import UsageStatistics

class ResearchResponse(BaseModel):
    """Response schema for the main `/research` endpoint."""
    model_config = ConfigDict(extra='ignore')
    report: str = Field(..., description="The final generated research report in Markdown format.")
    usage_statistics: UsageStatistics = Field(..., description="Detailed statistics about resource usage (tokens, cost, API calls).")

